### ISSUE TITLE
Parquet Connector - Need Documentation

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#367] opened 2023-02-28 21:29 UTC
I think a page should be created to describe all the intricacies of the Parquet connector. There are many to consider that go beyond the 1-line entry in the grid.

Most if not all other file formats have their dedicated pages linked from this overview page. The Parquet connector is more complex than, for example CSV, yet there is a details page for CSV and none for Parquet.

Right now the only way to figure out how the Parquet connector works is to try to reserve-engineer the behaviour based on experiments with Power Query. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72df40f2-3c58-cbda-79ec-c65ba5cc32ac
* Version Independent ID: ab483b41-107f-2027-c65f-63285a847c63
* Content: [List of all Power Query connectors - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/)
* Content Source: [powerquery-docs/connectors/index.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/connectors/index.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment] 2023-03-07 20:19
@VitalyMCT we're working on this. It might take a couple more weeks.

**Comment by DougKlopfenstein** [comment] 2023-08-07 17:59
Hi @VitalyMCT 
I'm closing the issue because Parquet connector information has been added to the connector articles in the Power Query documentation - [Parquet](https://learn.microsoft.com/power-query/connectors/parquet). If you believe that the issue isn't resolved, please feel free to reopen the issue.

**Closed by DougKlopfenstein** 2023-08-07 17:59 UTC
Labels: powerquery/svc, Pri1, doc-enhancement

**Comment by VitalyMCT** [comment] 2023-08-07 18:03
Thanks @DougKlopfenstein. I see the new Parquet connector page has been created.
