### ISSUE TITLE
Dataflow Error Message - More Queries Than We Recommend

### ISSUE THREAD

**Issue by joel-cooptimize** [MicrosoftDocs/powerquery-docs#323] opened 2022-11-16 17:51 UTC
"There are more queries in this project than we recommend."

A bit of feedback about this message.
1. Don't make me look at this warning message constantly. Not a good user experience.
2. The error message links to this article. The article doesn't say how many are recommended and why.
3. I don't have that many Dataflows, how small should it be? A dataflow per fact table?
4. Make improvements to Dataflows instead of investing in telling me I'm doing it wrong.

Thanks,

Joel
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76bbffdf-18f6-9001-b75a-57aedc1dcfe0
* Version Independent ID: 928761e0-8e55-c01f-9228-7ee5d2971d52
* Content: [Best practices for designing and developing complex dataflows - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/best-practices-developing-complex-dataflows)
* Content Source: [powerquery-docs/dataflows/best-practices-developing-complex-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/best-practices-developing-complex-dataflows.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment] 2022-12-09 20:20
Hi @joel-cooptimize This site was intended for the documentation team to improve the pages. 

I think these suggestions, which are excellent, are more oriented to the way the product works. I think the Ideas page is a better place to host the feedback to reach the right decision-makers. For Power BI: https://ideas.powerbi.com/ideas/

**Comment by joel-cooptimize** [comment] 2022-12-09 22:12
I understand. 

The article needs work too. The UI provides a vague warning message that links to the article, but the article doesn't reference the message.

**Comment by DougKlopfenstein** [comment] 2024-02-12 20:54
Thanks @joel-cooptimize for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. However, this appears to be product feedback or a request for product support. For information about product feedback or customer support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback). 

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Closed by DougKlopfenstein** 2024-02-12 20:54 UTC
Labels: product-feedback, powerquery/svc, Pri2
